name: Build VSCode extension

on:
  push:
    paths:
      - 'plush.tmbundle/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '>=20.x.x'
    
    - name: Install vsce
      run: npm install -g @vscode/vsce

    - name: Package .vsix
      run: cd plush.tmbundle && vsce package

    - name: Extract version
      run: echo "TAG=$(jq -r '.version' plush.tmbundle/package.json)" >> $GITHUB_ENV

    - name: Create Release
      run: gh release create $TAG 'plush.tmbundle/*.vsix' --generate-notes
      env:
        GH_TOKEN: ${{ github.token }}
