name: Build extension

on:
  push:
    paths:
      - 'plush.tmbundle/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '>=20.x.x'
    
    - name: Install vsce
      run: npm install -g @vscode/vsce

    - name: Extract version
      run: echo "TAG=$(jq -r '.version' plush.tmbundle/package.json)" >> $GITHUB_ENV

    - name: Create tag
      run: |
        git tag $TAG
        git push origin $TAG

    - name: Package .vsix
      run: cd tmbundle && vsce package

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG }}
        files: plush.tmbundle/*.vsix
